Q3DotNetAssiut/Controllers/DepartmentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Q3DotNetAssiut.Models;
using Q3DotNetAssiut.Repository;

namespace Q3DotNetAssiut.Controllers
{
    public class DepartmentController : Controller
    {
        // ITIContext context = new ITIContext();
        IDepartmentRepository DeptREpo;
        IEmployeeRepository EmployeeREpo;
        public DepartmentController(IDepartmentRepository deptRepo,IEmployeeRepository empRepo)///inject 
        {
            
            DeptREpo = deptRepo;// new DepartmentRepository();
            EmployeeREpo = empRepo;
            
        }

        public IActionResult DeptEmps()
        {
            return View("DeptEmps",DeptREpo.GetAll());//List<department>
        }

        //DEpartment/GetEmpsByDEptId?deptId=1
        public IActionResult GetEmpsByDEptId(int deptId)
        {
            List<Employee> EmpList= EmployeeREpo.GetByDEptID(deptId);
            return Json(EmpList);
        }






        [Authorize]
        public IActionResult Index()
        {
            List<Department> departmentList = DeptREpo.GetAll();
                //context.Department.Include(d=>d.Emps)
                //.ToList();
            return View("Index",departmentList);//Model List<department>
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View("Add");//Model Null
        }

        //Department/SAveAdd? Name = Sd & ManagerName = Ahmed
        //GEt Handel
        //Post HAndel
        [HttpPost]//Fillter
        public IActionResult SAveAdd(Department newDeptFromRequest)
        {
        
            if (newDeptFromRequest.Name != null)
            {
               DeptREpo.Add(newDeptFromRequest);
                DeptREpo.Save();
                return RedirectToAction("Index");
            }
            return View("Add", newDeptFromRequest);//Model DEpartment
            
        }
    }
}

Q3DotNetAssiut/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore;
using Q3DotNetAssiut.Models;
using Q3DotNetAssiut.Repository;
using Q3DotNetAssiut.ViewModel;

namespace Q3DotNetAssiut.Controllers
{
    public class EmployeeController : Controller
    {
        //  ITIContext context = new ITIContext();
        IDepartmentRepository DepartmentRepository;
        IEmployeeRepository EmployeeRepository;
        public EmployeeController(IDepartmentRepository deptReo, IEmployeeRepository EmpRepo)
        {
            DepartmentRepository = deptReo;
            EmployeeRepository = EmpRepo;
        }

        //Employee/EmpCardPartial/1   "Calling using ajax "Partial request"
        public IActionResult EmpCardPartial(int id)
        {
            return PartialView("_EmpCard",EmployeeRepository.GetById(id));//Model=Null
        }









        //Employee/CheckSalary?Salary=1000
        public IActionResult CheckSalary(int Salary,string JobTitle)
        {
            if (Salary > 6000 && JobTitle =="S")
                return Json(true);
            else if(JobTitle=="B" && Salary>10000)
                return Json(true);
            else if(JobTitle=="M" && Salary>40000)
                return Json(true);
            else
                return Json(false);
        }


        [HttpGet]
        public IActionResult NEw()
        {
            ViewData["DeptList"] =DepartmentRepository.GetAll();
            return View("New");
        }

        [HttpPost]
        public IActionResult SaveNEw(Employee EmpFromREquest)
        {
            if(ModelState.IsValid==true)
            {
                try
                {
                    //save
                    EmployeeRepository.Add(EmpFromREquest);
                    EmployeeRepository.Save();
                    return RedirectToAction("Index");
                }catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.InnerException.Message);
                }
            }
            ViewData["DeptList"] = DepartmentRepository.GetAll();
            return View("NEw", EmpFromREquest);
        }



        public IActionResult Index()
        {
            return View("Index",EmployeeRepository.GetAll());
        }

        //Hsandel Link
        public IActionResult Edit(int id,string name)
        {
            Employee EmpModel =
              EmployeeRepository.GetById(id);
            List<Department> DepartmentList = DepartmentRepository.GetAll();
            //-------------Create View Mode Mapping
            EmpWithDEptListViewModel EmpViewModel=new EmpWithDEptListViewModel();
            EmpViewModel.Id = EmpModel.Id;
            EmpViewModel.Name = EmpModel.Name;
            EmpViewModel.Address = EmpModel.Address;
            EmpViewModel.ImageURL = EmpModel.ImageURL;
            EmpViewModel.JobTitle = EmpModel.JobTitle;
            EmpViewModel.Salary = EmpModel.Salary; 
            EmpViewModel.DepartmentID = EmpModel.DepartmentID;

            EmpViewModel.DeptList = DepartmentList;

            return View("Edit", EmpViewModel);//Model EmpDeptListViewModel
        }
     
        [HttpPost]
        public IActionResult SaveEdit
            (int id,EmpWithDEptListViewModel EmpFromREquest)//Employee EmpFromREquest,int id)
        {
            if (EmpFromREquest.Name != null)
            {
                Employee EmpFromDB = EmployeeRepository.GetById(id);//context.Employee.FirstOrDefault(e => e.Id == id);
                EmpFromDB.Address=EmpFromREquest.Address;
                EmpFromDB.Name=EmpFromREquest.Name;
                EmpFromDB.Salary= EmpFromREquest.Salary;
                EmpFromDB.JobTitle= EmpFromREquest.JobTitle;
                EmpFromDB.ImageURL= EmpFromREquest.ImageURL;
                EmpFromDB.DepartmentID= EmpFromREquest.DepartmentID;
                EmpFromDB.Id= EmpFromREquest.Id;
                EmployeeRepository.Update(EmpFromDB);
                EmployeeRepository.Save();
                //context.SaveChanges();
                return RedirectToAction("Index");
            }
            //All Emp Data List<Department> 
            EmpFromREquest.DeptList = DepartmentRepository.GetAll();//context.Department.ToList();
            return View("Edit", EmpFromREquest);
        }







        public IActionResult Delete(int id)
        {
            return View("Delete",EmployeeRepository.GetById(id));
        }


        public IActionResult Details(int id)
        {
            string msg = "Hello From Action";
            int temp = 50;
            List<string> bracnches= new List<string>();
            
            bracnches.Add("Assiut");
            bracnches.Add("Alex");
            bracnches.Add("Cario");
            //Aditional info send to View from Action
            ViewData["Msg"] = msg;
            ViewData["Temp"] = temp;
            ViewData["brch"] = bracnches;
            
           
            ViewData["Color"] = "Blue";
            ViewBag.Color = "REd";
            //ViewData.Model=empMo
            Employee EmpMOdel = EmployeeRepository.GetById(id);// context.Employee.FirstOrDefault(e => e.Id == id);
            return View("Details", EmpMOdel);
        }


        public IActionResult DetailsVM(int id)
        {
            Employee empMOdel = EmployeeRepository.GetById(id);
                
            List<string> bracnches = new List<string>();

            bracnches.Add("Assiut");
            bracnches.Add("Alex");
            bracnches.Add("Cario");
            //decalre viewmode
            EmpDEptColorTempMSgBrchViewModel EmpVM = 
                new EmpDEptColorTempMSgBrchViewModel();
            //Mapping 
            EmpVM.EmpName = empMOdel.Name;
            EmpVM.DeptName = empMOdel.Department.Name;
            EmpVM.Color = "REd";
            EmpVM.Temp = 12;
            EmpVM.Msg = "Hello FRom VM";
            EmpVM.Branches = bracnches;
            return View("DetailsVM",EmpVM);//EmpDEptColorTempMSgBrchViewModel
        }
    }
}

Q3DotNetAssiut/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Q3DotNetAssiut.ViewModel;

namespace Q3DotNetAssiut.Controllers
{
    [Authorize(Roles ="Admin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;

        public RoleController(RoleManager<IdentityRole> roleManager)
        {
            this.roleManager = roleManager;
        }

        public IActionResult AddRole()
        {
            return View("AddRole");
        }
        [HttpPost]
        public async Task<IActionResult> SaveRole(RoleViewModel roleViewModel) {
            if(ModelState.IsValid)
            {
                IdentityRole role = new IdentityRole();
                role.Name = roleViewModel.RoleName;
                IdentityResult result= await roleManager.CreateAsync(role);
                if (result.Succeeded == true)
                {
                    ViewBag.sucess = true;
                    return View("AddRole");
                }
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError("", item.Description);
                }
            }
            return View("AddRole",roleViewModel);
        }

    }
}

Q3DotNetAssiut/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ITI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Q3DotNetAssiut.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <!--Using Html Helper @Html-->
        @* @Html.Partial("_NavPartial") *@
        @* @await Html.PartialAsync("_NavPartial") *@

       @*  @{
            // Html.RenderPartial("_NavPartial");
            await Html.RenderPartialAsync("_NavPartial");
        } *@
        
        <!--USing Tag Helper-->

        <partial name="_NavPartial" />
    </header>
    <div class="container">
        <main role="main" class="pb-3" style="border:2px solid red">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Q3DotNetAssiut - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Q3DotNetAssiut/Views/Shared/_MyLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div style="height:150px;background-color:burlywood;font-size:30px">Header
        <div style="background-color:darkcyan;">
            @RenderSection("HeadSection")
        </div>
    </div>
    <div style="height:300px;background-color:darkcyan;">
        @RenderBody()
    </div>
    <div style="height:50px;background-color:burlywood;font-size:40px">Footer
        <div style="background-color:darkcyan;">
            @RenderSection("FooterSection",false)
        </div>
    </div>
</body>
</html>

Q3DotNetAssiut/Views/Shared/_NavPartial.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Q3DotNetAssiut</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                </li>
                @if (User.Identity.IsAuthenticated == true)
                {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Department</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="SignOut">Log out</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="SignOut">Welcome @User.Identity.Name</a>
                    </li>
                    @if (User.IsInRole("Admin") == true)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="AddRole">Add Role</a>
                        </li>
                    }
                }
                else
                {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                    </li>
                }
            </ul>
        </div>
    </div>
</nav>